const trocas = [
  {
    data: "29/06/2023",
    id: 1,
    nomeCompleto: "João Silva",
    email: "joao.silva@example.com",
    idLivroEntrada: "123456",
    TituloLivroEntrada: "Yuri ",
    GeneroLivroEntrada: "Romance",
    idLivroSaida: "890",
    TituloLivroSaida: "Yuri ",
    GeneroLivroSaida: "Romance",
  },
  {
    data: "29/06/2023",
    id: 2,
    nomeCompleto: "Maria Souza",
    email: "maria.souza@example.com",
    idLivroEntrada: "123",
    TituloLivroEntrada: "Yuri ",
    GeneroLivroEntrada: "Romance",
    idLivroSaida: "890",
    TituloLivroSaida: "Yuri ",
    GeneroLivroSaida: "Romance",
  },
  {
    data: "29/06/2023",
    id: 3,
    nomeCompleto: "Carlos Ferreira",
    email: "carlos.ferreira@example.com",
    idLivroEntrada: "1234",
    TituloLivroEntrada: "Yuri ",
    GeneroLivroEntrada: "Romance",
    idLivroSaida: "890",
    TituloLivroSaida: "Yuri ",
    GeneroLivroSaida: "Romance",
  },
  {
    data: "29/06/2023",
    id: 4,
    nomeCompleto: "Ana Santos",
    email: "ana.santos@example.com",
    idLivroEntrada: "567",
    TituloLivroEntrada: "Yuri ",
    GeneroLivroEntrada: "Romance",
    idLivroSaida: "890",
    TituloLivroSaida: "Yuri ",
    GeneroLivroSaida: "Romance",
  },
  {
    data: "29/06/2023",
    id: 5,
    nomeCompleto: "Pedro Oliveira",
    email: "pedro.oliveira@example.com",
    idLivroEntrada: "890",
    TituloLivroEntrada: "Yuri ",
    GeneroLivroEntrada: "Romance",
    idLivroSaida: "890",
    TituloLivroSaida: "Yuri ",
    GeneroLivroSaida: "Romance",
  },
];

export default trocas;
