const usuarios = [
  {
    id: 1,
    nomeCompleto: "João Silva",
    email: "joao.silva@example.com",
    senha: "123456",
    imagem: "https://example.com/imagens/joao_silva.jpg",
    creditos: 5,
    ranking: 80,
    livrosDevolvidos: 3,
    pontos: 750,
  },
  {
    id: 2,
    nomeCompleto: "Maria Souza",
    email: "maria.souza@example.com",
    senha: "senha123",
    imagem: "https://example.com/imagens/maria_souza.jpg",
    creditos: 3,
    ranking: 65,
    livrosDevolvidos: 0,
    pontos: 500,
  },
  {
    id: 3,
    nomeCompleto: "Carlos Ferreira",
    email: "carlos.ferreira@example.com",
    senha: "senha1234",
    imagem: "https://example.com/imagens/carlos_ferreira.jpg",
    creditos: 2,
    ranking: 50,
    livrosDevolvidos: 1,
    pontos: 400,
  },
  {
    id: 4,
    nomeCompleto: "Ana Santos",
    email: "ana.santos@example.com",
    senha: "senha567",
    imagem: "https://example.com/imagens/ana_santos.jpg",
    creditos: 4,
    ranking: 75,
    livrosDevolvidos: 2,
    pontos: 600,
  },
  {
    id: 5,
    nomeCompleto: "Pedro Oliveira",
    email: "pedro.oliveira@example.com",
    senha: "senha890",
    imagem: "https://example.com/imagens/pedro_oliveira.jpg",
    creditos: 1,
    ranking: 40,
    livrosDevolvidos: 5,
    pontos: 300,
  },
  {
    id: 6,
    nomeCompleto: "Mariana Costa",
    email: "mariana.costa@example.com",
    senha: "senhaabc",
    imagem: "https://example.com/imagens/mariana_costa.jpg",
    creditos: 0,
    ranking: 30,
    livrosDevolvidos: 0,
    pontos: 200,
  },
  {
    id: 7,
    nomeCompleto: "Ricardo Almeida",
    email: "ricardo.almeida@example.com",
    senha: "senha456",
    imagem: "https://example.com/imagens/ricardo_almeida.jpg",
    creditos: 2,
    ranking: 55,
    livrosDevolvidos: 2,
    pontos: 450,
  },
  {
    id: 8,
    nomeCompleto: "Juliana Rodrigues",
    email: "juliana.rodrigues@example.com",
    senha: "senha321",
    imagem: "https://example.com/imagens/juliana_rodrigues.jpg",
    creditos: 3,
    ranking: 70,
    livrosDevolvidos: 1,
    pontos: 550,
  },
  {
    id: 11,
    nomeCompleto: "Fernanda Santos",
    email: "fernanda.santos@example.com",
    senha: "senha456",
    imagem: "https://example.com/imagens/fernanda_santos.jpg",
    creditos: 2,
    ranking: 60,
    livrosDevolvidos: 2,
    pontos: 400,
  },
  {
    id: 12,
    nomeCompleto: "Lucas Almeida",
    email: "lucas.almeida@example.com",
    senha: "senha789",
    imagem: "https://example.com/imagens/lucas_almeida.jpg",
    creditos: 1,
    ranking: 45,
    livrosDevolvidos: 1,
    pontos: 350,
  },
  {
    id: 13,
    nomeCompleto: "Isabela Gonçalves",
    email: "isabela.goncalves@example.com",
    senha: "senha321",
    imagem: "https://example.com/imagens/isabela_goncalves.jpg",
    creditos: 3,
    ranking: 70,
    livrosDevolvidos: 3,
    pontos: 600,
  },
  {
    id: 14,
    nomeCompleto: "Gustavo Lima",
    email: "gustavo.lima@example.com",
    senha: "senhaabc",
    imagem: "https://example.com/imagens/gustavo_lima.jpg",
    creditos: 2,
    ranking: 55,
    livrosDevolvidos: 0,
    pontos: 500,
  },
  {
    id: 15,
    nomeCompleto: "Amanda Costa",
    email: "amanda.costa@example.com",
    senha: "senha999",
    imagem: "https://example.com/imagens/amanda_costa.jpg",
    creditos: 4,
    ranking: 80,
    livrosDevolvidos: 4,
    pontos: 800,
  },
  {
    id: 16,
    nomeCompleto: "Rafael Oliveira",
    email: "rafael.oliveira@example.com",
    senha: "senha123",
    imagem: "https://example.com/imagens/rafael_oliveira.jpg",
    creditos: 2,
    ranking: 65,
    livrosDevolvidos: 2,
    pontos: 450,
  },
  {
    id: 17,
    nomeCompleto: "Natália Santos",
    email: "natalia.santos@example.com",
    senha: "senha567",
    imagem: "https://example.com/imagens/natalia_santos.jpg",
    creditos: 3,
    ranking: 70,
    livrosDevolvidos: 1,
    pontos: 550,
  },
  {
    id: 18,
    nomeCompleto: "Vinícius Rodrigues",
    email: "vinicius.rodrigues@example.com",
    senha: "senha789",
    imagem: "https://example.com/imagens/vinicius_rodrigues.jpg",
    creditos: 1,
    ranking: 40,
    livrosDevolvidos: 0,
    pontos: 300,
  },
];

export default usuarios;
